### ISSUE TITLE
Novi vic o odzacima

### ISSUE THREAD

**Issue by miljanic** [spsjvc/losi-vicevi#1]
## Neprijatnost
Iako bi mnogi pomislili da je neprijatnost dosla u trenutku kada su ljudi culi vic, varaju se. Naime, krenuo sam da ispricam drugarima tvoj novi vic o odzacima, ali sam ubrzo shvatio da sam ga zaboravio. Ali posto sam snalazljiv, brzo sam izvukao telefon iz dzepa i otvorio github mobilnu aplikaciju kako bih sto pre nasao vic. Istog trenutka me je oblio hladan znoj posto sam saznao da baza viceva nije up-to-date.

## Pojacanje
Da ne bih ja ili neko drugi dolazio u ovako neprijatne situacije, molim te da dodas ovaj vic u kolekciju. Ukoliko bilo kako mogu da ti pomognem oko ovoga a i inace u razvoju ovog projekta bila bi mi cast!

## Zahvalnica
Hvala ti na svom dosadasnjem trudu koji si ulozio u deljenje ovih losih viceva, meni su jako pomogli da prebrodim celu pandemiju, samo tako nastavi :heart:

**Comment by spsjvc** [comment]
Zbog ovakvih komentara i radim sve ovo. Hvala ti. ❤️
